In [1]:
import torch
import torch.nn as nn
import math
import numpy as np

In [ ]:
def add(num):
    return num +1


x = 3
for i in range(10):
    x = add(x)
print(x) 

In [6]:
pe = torch.randn(3, 2, 5,4)
pe

tensor([[[[-1.0047, -0.7807,  0.1880, -0.3930],
          [ 0.4722, -0.0091, -0.4450,  1.6333],
          [ 2.3372, -0.6267,  1.8028, -1.3613],
          [ 0.6666, -1.1908, -0.9757,  1.2225],
          [-0.4613,  0.7895, -1.2481,  0.7646]],

         [[-1.3025,  0.4203, -0.0255,  0.7328],
          [-0.5811, -0.2708,  0.3745,  1.0871],
          [-0.1778, -0.5846, -0.2572, -0.8767],
          [-1.3432,  1.5392,  1.2854, -0.0635],
          [ 1.2638, -3.3395, -0.7382, -0.6187]]],


        [[[ 1.0643, -0.0551,  1.2864,  0.6277],
          [-0.0150,  0.6234,  2.1793,  0.4823],
          [-1.8973,  0.7574,  1.7489, -1.1594],
          [-0.0147, -0.7052,  0.9326,  1.0854],
          [ 1.0071, -0.4347, -0.1676, -0.7953]],

         [[ 1.0296, -0.9789, -0.0435,  2.7295],
          [-0.6247, -1.2609,  1.0908,  1.4704],
          [ 0.1000, -0.3370,  1.0904,  0.2444],
          [-0.6861, -0.2694,  0.1435, -1.5676],
          [-0.9505, -0.0075, -0.9708,  0.2709]]],


        [[[-0.1684, -0.5224,

In [8]:
pe = torch.softmax(pe, dim=-1)
pe

tensor([[[[0.2213, 0.2289, 0.3019, 0.2480],
          [0.2302, 0.2139, 0.2052, 0.3507],
          [0.3447, 0.1948, 0.2687, 0.1917],
          [0.2629, 0.2001, 0.2026, 0.3344],
          [0.2165, 0.2918, 0.2029, 0.2888]],

         [[0.2040, 0.2640, 0.2358, 0.2962],
          [0.2116, 0.2193, 0.2473, 0.3218],
          [0.2686, 0.2411, 0.2621, 0.2282],
          [0.1965, 0.3126, 0.2799, 0.2110],
          [0.4000, 0.1865, 0.2054, 0.2081]]],


        [[[0.2640, 0.2142, 0.2852, 0.2366],
          [0.2032, 0.2171, 0.3666, 0.2131],
          [0.1907, 0.2418, 0.3730, 0.1945],
          [0.2218, 0.2067, 0.2772, 0.2943],
          [0.3423, 0.2191, 0.2285, 0.2101]],

         [[0.2129, 0.1880, 0.1937, 0.4053],
          [0.2034, 0.1972, 0.2745, 0.3249],
          [0.2311, 0.2167, 0.3145, 0.2377],
          [0.2337, 0.2580, 0.2993, 0.2089],
          [0.2189, 0.2667, 0.2184, 0.2959]]],


        [[[0.2336, 0.2202, 0.2173, 0.3289],
          [0.2237, 0.2226, 0.2680, 0.2857],
          [0.3199, 0

In [13]:
from tokenizers import Tokenizer
from tokenizers.models import BPE
from tokenizers.pre_tokenizers import Whitespace
from datasets import load_dataset

def get_story_in_lang(lang):
    ds_raw = load_dataset('opus_books', 'en-it', split = 'train')
    for item in ds_raw:
        yield item['translation'][lang]



tokenizer = Tokenizer(BPE(unk_token="[UNK]"))
from tokenizers.trainers import BpeTrainer
trainer = BpeTrainer(special_tokens=["[UNK]", "[SOS]", "[EOS]", "[PAD]"])

tokenizer.pre_tokenizer = Whitespace()

tokenizer.train_from_iterator(get_story_in_lang('en'), trainer = trainer)
tokenizer.save("tokenizer-wiki.json")


In [12]:
j = torch.pow(10,  torch.arange(0,5)*-4/512)
j

tensor([1.0000e+00, 2.5119e-02, 6.3096e-04, 1.5849e-05, 3.9811e-07])

In [9]:
pe = torch.ones(2, 5,4)


pe[: ,:] / (10000**((2*torch.arange(1, 6).unsqueeze(1)/512)))


tensor([[[0.9647, 0.9647, 0.9647, 0.9647],
         [0.9306, 0.9306, 0.9306, 0.9306],
         [0.8977, 0.8977, 0.8977, 0.8977],
         [0.8660, 0.8660, 0.8660, 0.8660],
         [0.8354, 0.8354, 0.8354, 0.8354]],

        [[0.9647, 0.9647, 0.9647, 0.9647],
         [0.9306, 0.9306, 0.9306, 0.9306],
         [0.8977, 0.8977, 0.8977, 0.8977],
         [0.8660, 0.8660, 0.8660, 0.8660],
         [0.8354, 0.8354, 0.8354, 0.8354]]])

In [13]:
div_term = torch.exp(torch.arange(0, 5, 2) * -(np.log(10000.0) / 5))
div_term

tensor([1.0000e+00, 2.5119e-02, 6.3096e-04])

In [5]:
torch.arange(0, 5, 2) 

tensor([0, 2, 4])

In [2]:
l  = torch.arange(5).unsqueeze(1)
l

tensor([[0],
        [1],
        [2],
        [3],
        [4]])

In [15]:
div_term = torch.exp(torch.arange(0, 6, 2) * -(math.log(10000.0) / 3))
div_term


tensor([1.0000e+00, 2.1544e-03, 4.6416e-06])

In [29]:
pe = torch.ones(5,6)
pe

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [30]:
pe[:,0::2] = torch.sin(l/div_term)
pe[:, 1::2] = torch.cos(l/div_term)

In [31]:
pe

tensor([[ 0.0000,  1.0000,  0.0000,  1.0000,  0.0000,  1.0000],
        [ 0.8415,  0.5403, -0.7151,  0.6990, -0.6469,  0.7626],
        [ 0.9093, -0.4161, -0.9997, -0.0229, -0.9866,  0.1631],
        [ 0.1411, -0.9900, -0.6824, -0.7310, -0.8579, -0.5139],
        [-0.7568, -0.6536,  0.0457, -0.9990, -0.3218, -0.9468]])

In [9]:
pe = pe[:,0::2] * div_term

tensor([ 4.,  9., 16.])


In [32]:
x =  torch.ones(3, 5,3)
x

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [26]:
y = torch.ones(1, 5)
y

tensor([[1., 1., 1., 1., 1.]])

In [45]:
import torch

# Create a tensor
tensor = torch.arange(12).reshape(3, 4)  # Example tensor of shape (3, 4)

# Define the number of parts (n)
n = 2


print(tensor.size(1))
# Calculate the number of columns per part
columns_per_part = tensor.size(1) // n

# Split the tensor into n parts horizontally
parts = torch.split(tensor, columns_per_part, dim=1)

print(parts)









4
(tensor([[0, 1],
        [4, 5],
        [8, 9]]), tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]]))


In [14]:
original_tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7,8,9]])
original_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [21]:
reshaped_tensor = original_tensor.view(1, 6)
reshaped_tensor

RuntimeError: shape '[1, 6]' is invalid for input of size 9

In [9]:
# Assuming you have a tensor with 8 columns
original_tensor = torch.randn((4,3,12))  # 10 rows, 8 columns

# Reshape into two tensors with 4 columns each
# tensor1 = original_tensor.view(10, 4)
# tensor2 = original_tensor.view(10, 4, 4)

In [10]:
original_tensor

tensor([[[ 0.3747, -0.3154,  1.9973,  1.5016,  0.1367,  0.7747, -0.4879,
          -2.2326, -0.3182, -1.1270, -1.4711, -0.3569],
         [-0.8798,  0.6050,  0.5201,  1.5696, -1.1369,  1.2308, -0.3219,
           1.2360, -0.4541,  0.9117, -1.5560, -0.5282],
         [ 0.0861, -0.6723,  2.0650, -0.3342, -0.1066, -0.9368,  0.0530,
           1.0489,  0.7111, -0.4072, -0.1465,  0.5948]],

        [[-0.5127,  0.5897,  3.1053,  0.6968,  0.6136, -0.1065,  0.1887,
           0.7772,  1.0469,  0.8286, -0.1791,  1.1441],
         [ 0.3378,  0.5325, -0.1929,  0.0176,  0.5653,  1.3824,  1.2239,
           1.4021,  0.2207,  0.1849, -0.9061,  0.4841],
         [ 1.2226,  1.5711, -0.4486,  0.2924,  0.1485, -0.8486, -0.1540,
          -1.4175,  0.2750, -0.7457,  0.3570, -0.7237]],

        [[-0.7684, -0.5854, -1.2868, -0.5021,  0.2955, -1.0912,  0.0700,
           1.5920,  0.0055,  0.3954, -0.1545,  0.1759],
         [ 2.0958, -1.1765,  0.7071,  2.3668,  0.2622, -0.1157, -1.6553,
          -0.3449,  

In [16]:
k = original_tensor.view(original_tensor.shape[0], original_tensor.shape[1], 4, 3).transpose(1,2)
k

tensor([[[[ 0.3747, -0.3154,  1.9973],
          [-0.8798,  0.6050,  0.5201],
          [ 0.0861, -0.6723,  2.0650]],

         [[ 1.5016,  0.1367,  0.7747],
          [ 1.5696, -1.1369,  1.2308],
          [-0.3342, -0.1066, -0.9368]],

         [[-0.4879, -2.2326, -0.3182],
          [-0.3219,  1.2360, -0.4541],
          [ 0.0530,  1.0489,  0.7111]],

         [[-1.1270, -1.4711, -0.3569],
          [ 0.9117, -1.5560, -0.5282],
          [-0.4072, -0.1465,  0.5948]]],


        [[[-0.5127,  0.5897,  3.1053],
          [ 0.3378,  0.5325, -0.1929],
          [ 1.2226,  1.5711, -0.4486]],

         [[ 0.6968,  0.6136, -0.1065],
          [ 0.0176,  0.5653,  1.3824],
          [ 0.2924,  0.1485, -0.8486]],

         [[ 0.1887,  0.7772,  1.0469],
          [ 1.2239,  1.4021,  0.2207],
          [-0.1540, -1.4175,  0.2750]],

         [[ 0.8286, -0.1791,  1.1441],
          [ 0.1849, -0.9061,  0.4841],
          [-0.7457,  0.3570, -0.7237]]],


        [[[-0.7684, -0.5854, -1.2868],
     

In [11]:
#this sapes the tensor into (batch, num_heads, seq_len, d_k)
# 4,4,3,3
j = original_tensor.view(4, 3,4, 3)
j

tensor([[[[ 0.3747, -0.3154,  1.9973],
          [ 1.5016,  0.1367,  0.7747],
          [-0.4879, -2.2326, -0.3182],
          [-1.1270, -1.4711, -0.3569]],

         [[-0.8798,  0.6050,  0.5201],
          [ 1.5696, -1.1369,  1.2308],
          [-0.3219,  1.2360, -0.4541],
          [ 0.9117, -1.5560, -0.5282]],

         [[ 0.0861, -0.6723,  2.0650],
          [-0.3342, -0.1066, -0.9368],
          [ 0.0530,  1.0489,  0.7111],
          [-0.4072, -0.1465,  0.5948]]],


        [[[-0.5127,  0.5897,  3.1053],
          [ 0.6968,  0.6136, -0.1065],
          [ 0.1887,  0.7772,  1.0469],
          [ 0.8286, -0.1791,  1.1441]],

         [[ 0.3378,  0.5325, -0.1929],
          [ 0.0176,  0.5653,  1.3824],
          [ 1.2239,  1.4021,  0.2207],
          [ 0.1849, -0.9061,  0.4841]],

         [[ 1.2226,  1.5711, -0.4486],
          [ 0.2924,  0.1485, -0.8486],
          [-0.1540, -1.4175,  0.2750],
          [-0.7457,  0.3570, -0.7237]]],


        [[[-0.7684, -0.5854, -1.2868],
         

In [35]:
j = original_tensor.view(4, 3,4, 3).transpose(2,1)
j.shape

torch.Size([4, 4, 3, 3])

In [36]:
j = j.transpose(2,1)
j.reshape(j.shape[0], j.shape[1], 3*4)

tensor([[[ 0.3747, -0.3154,  1.9973,  1.5016,  0.1367,  0.7747, -0.4879,
          -2.2326, -0.3182, -1.1270, -1.4711, -0.3569],
         [-0.8798,  0.6050,  0.5201,  1.5696, -1.1369,  1.2308, -0.3219,
           1.2360, -0.4541,  0.9117, -1.5560, -0.5282],
         [ 0.0861, -0.6723,  2.0650, -0.3342, -0.1066, -0.9368,  0.0530,
           1.0489,  0.7111, -0.4072, -0.1465,  0.5948]],

        [[-0.5127,  0.5897,  3.1053,  0.6968,  0.6136, -0.1065,  0.1887,
           0.7772,  1.0469,  0.8286, -0.1791,  1.1441],
         [ 0.3378,  0.5325, -0.1929,  0.0176,  0.5653,  1.3824,  1.2239,
           1.4021,  0.2207,  0.1849, -0.9061,  0.4841],
         [ 1.2226,  1.5711, -0.4486,  0.2924,  0.1485, -0.8486, -0.1540,
          -1.4175,  0.2750, -0.7457,  0.3570, -0.7237]],

        [[-0.7684, -0.5854, -1.2868, -0.5021,  0.2955, -1.0912,  0.0700,
           1.5920,  0.0055,  0.3954, -0.1545,  0.1759],
         [ 2.0958, -1.1765,  0.7071,  2.3668,  0.2622, -0.1157, -1.6553,
          -0.3449,  

In [2]:
aj = torch.randn(3,2)
aj

tensor([[ 1.0987, -0.9672],
        [-0.8051,  1.3027],
        [-0.7114,  0.5448]])

In [4]:
jk =torch.mean(aj, dim=1)
jk.unsqueeze(1)

tensor([[ 0.0657],
        [ 0.2488],
        [-0.0833]])

In [17]:
input_tensor = torch.tensor([[1, 2, 3],
                             [4, 0, 0],
                             [5, 6, 0]])

In [24]:
# Define the padding value
padding_value = 3

# Create the padding mask
padding_mask = (input_tensor != padding_value).int()
print(padding_mask)

masked_tensor = input_tensor * padding_mask

print(masked_tensor)








tensor([[1, 1, 0],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
tensor([[1, 2, 0],
        [4, 0, 0],
        [5, 6, 0]])


In [44]:
j = torch.zeros(5,6)
j

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [45]:
t = torch.ones(3,4, 5,6)
t.shape
f = t * j
print(f)

tensor([[[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0

In [54]:
l = nn.Embedding(10,2, padding_idx=5)
l(torch.tensor([5]))

tensor([[0., 0.]], grad_fn=<EmbeddingBackward0>)

In [8]:
f = torch.ones(3,5)
f



tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [9]:
j = torch.ones(4, 3,5)
j



tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [10]:
f + j

tensor([[[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]],

        [[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]],

        [[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]],

        [[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]]])