In [1]:
import torch
import torch.nn as nn
import math
import numpy as np

In [13]:
from tokenizers import Tokenizer
from tokenizers.models import BPE
from tokenizers.pre_tokenizers import Whitespace
from datasets import load_dataset

def get_story_in_lang(lang):
    ds_raw = load_dataset('opus_books', 'en-it', split = 'train')
    for item in ds_raw:
        yield item['translation'][lang]



tokenizer = Tokenizer(BPE(unk_token="[UNK]"))
from tokenizers.trainers import BpeTrainer
trainer = BpeTrainer(special_tokens=["[UNK]", "[SOS]", "[EOS]", "[PAD]"])

tokenizer.pre_tokenizer = Whitespace()

tokenizer.train_from_iterator(get_story_in_lang('en'), trainer = trainer)
tokenizer.save("tokenizer-wiki.json")


In [12]:
j = torch.pow(10,  torch.arange(0,5)*-4/512)
j

tensor([1.0000e+00, 2.5119e-02, 6.3096e-04, 1.5849e-05, 3.9811e-07])

In [9]:
pe = torch.ones(2, 5,4)


pe[: ,:] / (10000**((2*torch.arange(1, 6).unsqueeze(1)/512)))


tensor([[[0.9647, 0.9647, 0.9647, 0.9647],
         [0.9306, 0.9306, 0.9306, 0.9306],
         [0.8977, 0.8977, 0.8977, 0.8977],
         [0.8660, 0.8660, 0.8660, 0.8660],
         [0.8354, 0.8354, 0.8354, 0.8354]],

        [[0.9647, 0.9647, 0.9647, 0.9647],
         [0.9306, 0.9306, 0.9306, 0.9306],
         [0.8977, 0.8977, 0.8977, 0.8977],
         [0.8660, 0.8660, 0.8660, 0.8660],
         [0.8354, 0.8354, 0.8354, 0.8354]]])

In [13]:
div_term = torch.exp(torch.arange(0, 5, 2) * -(np.log(10000.0) / 5))
div_term

tensor([1.0000e+00, 2.5119e-02, 6.3096e-04])

In [5]:
torch.arange(0, 5, 2) 

tensor([0, 2, 4])

In [2]:
l  = torch.arange(5).unsqueeze(1)
l

tensor([[0],
        [1],
        [2],
        [3],
        [4]])

In [15]:
div_term = torch.exp(torch.arange(0, 6, 2) * -(math.log(10000.0) / 3))
div_term


tensor([1.0000e+00, 2.1544e-03, 4.6416e-06])

In [29]:
pe = torch.ones(5,6)
pe

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [30]:
pe[:,0::2] = torch.sin(l/div_term)
pe[:, 1::2] = torch.cos(l/div_term)

In [31]:
pe

tensor([[ 0.0000,  1.0000,  0.0000,  1.0000,  0.0000,  1.0000],
        [ 0.8415,  0.5403, -0.7151,  0.6990, -0.6469,  0.7626],
        [ 0.9093, -0.4161, -0.9997, -0.0229, -0.9866,  0.1631],
        [ 0.1411, -0.9900, -0.6824, -0.7310, -0.8579, -0.5139],
        [-0.7568, -0.6536,  0.0457, -0.9990, -0.3218, -0.9468]])

In [9]:
pe = pe[:,0::2] * div_term

tensor([ 4.,  9., 16.])


In [32]:
x =  torch.ones(3, 5,3)
x

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [26]:
y = torch.ones(1, 5)
y

tensor([[1., 1., 1., 1., 1.]])

In [45]:
import torch

# Create a tensor
tensor = torch.arange(12).reshape(3, 4)  # Example tensor of shape (3, 4)

# Define the number of parts (n)
n = 2


print(tensor.size(1))
# Calculate the number of columns per part
columns_per_part = tensor.size(1) // n

# Split the tensor into n parts horizontally
parts = torch.split(tensor, columns_per_part, dim=1)

print(parts)









4
(tensor([[0, 1],
        [4, 5],
        [8, 9]]), tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]]))


In [14]:
original_tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7,8,9]])
original_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [21]:
reshaped_tensor = original_tensor.view(1, 6)
reshaped_tensor

RuntimeError: shape '[1, 6]' is invalid for input of size 9

In [3]:
# Assuming you have a tensor with 8 columns
original_tensor = torch.randn((4,3,12))  # 10 rows, 8 columns

# Reshape into two tensors with 4 columns each
# tensor1 = original_tensor.view(10, 4)
# tensor2 = original_tensor.view(10, 4, 4)

In [4]:
original_tensor

tensor([[[ 0.1594, -0.0982,  0.1846, -1.8004, -0.0822, -0.3025, -0.7025,
           0.0107, -0.0184, -2.0366,  0.6708,  0.3827],
         [-0.3038, -0.9654,  1.2087,  0.3216,  0.3969, -1.9447, -1.4017,
          -0.0270,  0.7832,  1.1486, -1.7278, -0.8070],
         [ 0.2152, -1.5515, -0.7535,  0.6273, -1.0386, -1.2060, -1.0963,
           0.8710, -1.8924,  1.0543, -0.2662, -0.1385]],

        [[-0.2147,  1.0707, -0.3061,  0.2757,  0.8054,  1.5964, -0.8827,
           0.9234,  0.2430, -0.9465, -1.1662, -0.6612],
         [-0.4192, -0.9518,  0.2493,  0.6738,  1.3270, -0.8107, -0.9641,
          -0.8406,  0.3892,  1.1731, -0.2494, -0.0136],
         [ 0.0329,  2.2602, -0.4044, -0.0454,  0.6857,  0.1848, -0.3324,
           2.0475,  1.8617, -2.8065,  0.2292, -0.6965]],

        [[ 1.6476, -0.7981, -0.5466,  0.1786,  0.5443,  0.2805, -1.6224,
          -0.0587,  1.5927,  0.5001, -0.7675, -0.5726],
         [-1.1786,  0.0734, -0.7836,  0.8479, -0.0098, -0.8698,  0.0315,
           0.3066,  

In [5]:
#this sapes the tensor into (batch, num_heads, seq_len, d_k)
# 4,4,3,3
j = original_tensor.view(4, 3,4, 3)
j

tensor([[[[ 0.1594, -0.0982,  0.1846],
          [-1.8004, -0.0822, -0.3025],
          [-0.7025,  0.0107, -0.0184],
          [-2.0366,  0.6708,  0.3827]],

         [[-0.3038, -0.9654,  1.2087],
          [ 0.3216,  0.3969, -1.9447],
          [-1.4017, -0.0270,  0.7832],
          [ 1.1486, -1.7278, -0.8070]],

         [[ 0.2152, -1.5515, -0.7535],
          [ 0.6273, -1.0386, -1.2060],
          [-1.0963,  0.8710, -1.8924],
          [ 1.0543, -0.2662, -0.1385]]],


        [[[-0.2147,  1.0707, -0.3061],
          [ 0.2757,  0.8054,  1.5964],
          [-0.8827,  0.9234,  0.2430],
          [-0.9465, -1.1662, -0.6612]],

         [[-0.4192, -0.9518,  0.2493],
          [ 0.6738,  1.3270, -0.8107],
          [-0.9641, -0.8406,  0.3892],
          [ 1.1731, -0.2494, -0.0136]],

         [[ 0.0329,  2.2602, -0.4044],
          [-0.0454,  0.6857,  0.1848],
          [-0.3324,  2.0475,  1.8617],
          [-2.8065,  0.2292, -0.6965]]],


        [[[ 1.6476, -0.7981, -0.5466],
         

In [6]:
j = original_tensor.view(4, 3,4, 3).transpose(2,1)
j

tensor([[[[ 0.1594, -0.0982,  0.1846],
          [-0.3038, -0.9654,  1.2087],
          [ 0.2152, -1.5515, -0.7535]],

         [[-1.8004, -0.0822, -0.3025],
          [ 0.3216,  0.3969, -1.9447],
          [ 0.6273, -1.0386, -1.2060]],

         [[-0.7025,  0.0107, -0.0184],
          [-1.4017, -0.0270,  0.7832],
          [-1.0963,  0.8710, -1.8924]],

         [[-2.0366,  0.6708,  0.3827],
          [ 1.1486, -1.7278, -0.8070],
          [ 1.0543, -0.2662, -0.1385]]],


        [[[-0.2147,  1.0707, -0.3061],
          [-0.4192, -0.9518,  0.2493],
          [ 0.0329,  2.2602, -0.4044]],

         [[ 0.2757,  0.8054,  1.5964],
          [ 0.6738,  1.3270, -0.8107],
          [-0.0454,  0.6857,  0.1848]],

         [[-0.8827,  0.9234,  0.2430],
          [-0.9641, -0.8406,  0.3892],
          [-0.3324,  2.0475,  1.8617]],

         [[-0.9465, -1.1662, -0.6612],
          [ 1.1731, -0.2494, -0.0136],
          [-2.8065,  0.2292, -0.6965]]],


        [[[ 1.6476, -0.7981, -0.5466],
     

In [7]:
j.transpose(2,1).view(j.shape[0], j.shape[2], 12)

tensor([[[ 0.1594, -0.0982,  0.1846, -1.8004, -0.0822, -0.3025, -0.7025,
           0.0107, -0.0184, -2.0366,  0.6708,  0.3827],
         [-0.3038, -0.9654,  1.2087,  0.3216,  0.3969, -1.9447, -1.4017,
          -0.0270,  0.7832,  1.1486, -1.7278, -0.8070],
         [ 0.2152, -1.5515, -0.7535,  0.6273, -1.0386, -1.2060, -1.0963,
           0.8710, -1.8924,  1.0543, -0.2662, -0.1385]],

        [[-0.2147,  1.0707, -0.3061,  0.2757,  0.8054,  1.5964, -0.8827,
           0.9234,  0.2430, -0.9465, -1.1662, -0.6612],
         [-0.4192, -0.9518,  0.2493,  0.6738,  1.3270, -0.8107, -0.9641,
          -0.8406,  0.3892,  1.1731, -0.2494, -0.0136],
         [ 0.0329,  2.2602, -0.4044, -0.0454,  0.6857,  0.1848, -0.3324,
           2.0475,  1.8617, -2.8065,  0.2292, -0.6965]],

        [[ 1.6476, -0.7981, -0.5466,  0.1786,  0.5443,  0.2805, -1.6224,
          -0.0587,  1.5927,  0.5001, -0.7675, -0.5726],
         [-1.1786,  0.0734, -0.7836,  0.8479, -0.0098, -0.8698,  0.0315,
           0.3066,  

In [2]:
aj = torch.randn(3,2)
aj

tensor([[ 1.0987, -0.9672],
        [-0.8051,  1.3027],
        [-0.7114,  0.5448]])

In [4]:
jk =torch.mean(aj, dim=1)
jk.unsqueeze(1)

tensor([[ 0.0657],
        [ 0.2488],
        [-0.0833]])

In [17]:
input_tensor = torch.tensor([[1, 2, 3],
                             [4, 0, 0],
                             [5, 6, 0]])

In [24]:
# Define the padding value
padding_value = 3

# Create the padding mask
padding_mask = (input_tensor != padding_value).int()
print(padding_mask)

masked_tensor = input_tensor * padding_mask

print(masked_tensor)








tensor([[1, 1, 0],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
tensor([[1, 2, 0],
        [4, 0, 0],
        [5, 6, 0]])


In [44]:
j = torch.zeros(5,6)
j

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [45]:
t = torch.ones(3,4, 5,6)
t.shape
f = t * j
print(f)

tensor([[[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0

In [54]:
l = nn.Embedding(10,2, padding_idx=5)
l(torch.tensor([5]))

tensor([[0., 0.]], grad_fn=<EmbeddingBackward0>)

In [8]:
f = torch.ones(3,5)
f



tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [9]:
j = torch.ones(4, 3,5)
j



tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [10]:
f + j

tensor([[[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]],

        [[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]],

        [[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]],

        [[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]]])