In [7]:
import torch
import torch.nn as nn
import math
import numpy as np

In [1]:
def add(num):
    return num +1


x = 3
for i in range(10):
    x = add(x)
print(x) 

13


In [44]:
pe = torch.randn(3,5,4)
pe

tensor([[[ 1.3702, -0.9734, -2.0180, -1.7274],
         [-1.0941, -0.3457, -0.4963, -1.3405],
         [ 0.9665, -0.1556, -0.1646, -1.1247],
         [ 0.5573, -1.1089, -1.4305, -0.1664],
         [-1.3292, -0.1934,  1.1951,  0.4222]],

        [[ 1.0810,  1.2269,  0.8059,  0.0886],
         [ 0.4564,  0.8382, -0.8297,  0.2976],
         [ 0.6037,  0.5643,  0.8450,  0.3196],
         [ 0.0700, -0.8949,  0.9775,  0.6022],
         [ 2.3541,  0.3687,  0.9792,  0.4612]],

        [[ 0.6204, -0.4519,  0.2207, -0.2403],
         [-1.4087,  1.3106,  1.7071,  0.1296],
         [-0.9428, -1.3478,  0.8620, -0.8970],
         [-1.9424,  1.9631, -1.5458,  0.9840],
         [ 0.9040, -0.1328, -0.3945, -1.4670]]])

In [45]:
pe.softmax( dim=-1)


tensor([[[0.8511, 0.0817, 0.0287, 0.0384],
         [0.1750, 0.3699, 0.3182, 0.1368],
         [0.5644, 0.1838, 0.1821, 0.0697],
         [0.5522, 0.1043, 0.0757, 0.2678],
         [0.0447, 0.1393, 0.5583, 0.2577]],

        [[0.3042, 0.3520, 0.2310, 0.1128],
         [0.2782, 0.4076, 0.0769, 0.2374],
         [0.2508, 0.2411, 0.3193, 0.1888],
         [0.1798, 0.0685, 0.4456, 0.3061],
         [0.6490, 0.0891, 0.1641, 0.0978]],

        [[0.4106, 0.1405, 0.2753, 0.1736],
         [0.0231, 0.3497, 0.5199, 0.1074],
         [0.1137, 0.0759, 0.6914, 0.1191],
         [0.0141, 0.7014, 0.0210, 0.2635],
         [0.5811, 0.2060, 0.1586, 0.0543]]])

In [39]:
pe.view(-1, 4)

tensor([[ 0.1186,  0.0817, -0.7493, -0.1087],
        [ 0.6830, -0.5266, -1.2983,  0.2962],
        [-1.5785,  0.7623,  0.0662, -0.4074],
        [-0.1217,  0.0666, -0.3907,  0.0965],
        [-1.6425,  0.0318, -1.2116,  1.5726],
        [-0.0526, -0.1219, -0.4346,  0.4086],
        [ 0.0985,  0.5565, -0.7304,  0.1291],
        [ 0.5877, -1.4460,  0.3380,  1.2966],
        [ 0.0391,  1.9948,  0.5572, -0.0736],
        [ 1.0560,  2.0222,  1.4077,  0.0784],
        [-0.9867,  0.3948, -2.8570,  0.2800],
        [ 0.0875,  1.5100,  1.6393, -1.0153],
        [-0.2597, -0.1747,  0.7246, -0.2850],
        [ 0.3620, -0.3157,  0.3002,  1.1716],
        [ 0.6559,  0.9599, -0.2290,  1.1106]])

In [42]:
lab = torch.randn(3,5)
lab

tensor([[ 0.8638, -0.8031, -1.7960, -0.0873,  0.2826],
        [ 1.4938,  1.7694,  0.3406,  0.6390, -0.3245],
        [ 1.0373,  0.5098,  2.0853,  1.9720, -0.3262]])

In [43]:
lab.view(-1,)

tensor([ 0.8638, -0.8031, -1.7960, -0.0873,  0.2826,  1.4938,  1.7694,  0.3406,
         0.6390, -0.3245,  1.0373,  0.5098,  2.0853,  1.9720, -0.3262])

In [13]:
from tokenizers import Tokenizer
from tokenizers.models import BPE
from tokenizers.pre_tokenizers import Whitespace
from datasets import load_dataset

def get_story_in_lang(lang):
    ds_raw = load_dataset('opus_books', 'en-it', split = 'train')
    for item in ds_raw:
        yield item['translation'][lang]



tokenizer = Tokenizer(BPE(unk_token="[UNK]"))
from tokenizers.trainers import BpeTrainer
trainer = BpeTrainer(special_tokens=["[UNK]", "[SOS]", "[EOS]", "[PAD]"])

tokenizer.pre_tokenizer = Whitespace()

tokenizer.train_from_iterator(get_story_in_lang('en'), trainer = trainer)
tokenizer.save("tokenizer-wiki.json")


In [12]:
j = torch.pow(10,  torch.arange(0,5)*-4/512)
j

tensor([1.0000e+00, 2.5119e-02, 6.3096e-04, 1.5849e-05, 3.9811e-07])

In [9]:
pe = torch.ones(2, 5,4)


pe[: ,:] / (10000**((2*torch.arange(1, 6).unsqueeze(1)/512)))


tensor([[[0.9647, 0.9647, 0.9647, 0.9647],
         [0.9306, 0.9306, 0.9306, 0.9306],
         [0.8977, 0.8977, 0.8977, 0.8977],
         [0.8660, 0.8660, 0.8660, 0.8660],
         [0.8354, 0.8354, 0.8354, 0.8354]],

        [[0.9647, 0.9647, 0.9647, 0.9647],
         [0.9306, 0.9306, 0.9306, 0.9306],
         [0.8977, 0.8977, 0.8977, 0.8977],
         [0.8660, 0.8660, 0.8660, 0.8660],
         [0.8354, 0.8354, 0.8354, 0.8354]]])

In [13]:
div_term = torch.exp(torch.arange(0, 5, 2) * -(np.log(10000.0) / 5))
div_term

tensor([1.0000e+00, 2.5119e-02, 6.3096e-04])

In [5]:
torch.arange(0, 5, 2) 

tensor([0, 2, 4])

In [2]:
l  = torch.arange(5).unsqueeze(1)
l

tensor([[0],
        [1],
        [2],
        [3],
        [4]])

In [15]:
div_term = torch.exp(torch.arange(0, 6, 2) * -(math.log(10000.0) / 3))
div_term


tensor([1.0000e+00, 2.1544e-03, 4.6416e-06])

In [29]:
pe = torch.ones(5,6)
pe

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [30]:
pe[:,0::2] = torch.sin(l/div_term)
pe[:, 1::2] = torch.cos(l/div_term)

In [31]:
pe

tensor([[ 0.0000,  1.0000,  0.0000,  1.0000,  0.0000,  1.0000],
        [ 0.8415,  0.5403, -0.7151,  0.6990, -0.6469,  0.7626],
        [ 0.9093, -0.4161, -0.9997, -0.0229, -0.9866,  0.1631],
        [ 0.1411, -0.9900, -0.6824, -0.7310, -0.8579, -0.5139],
        [-0.7568, -0.6536,  0.0457, -0.9990, -0.3218, -0.9468]])

In [9]:
pe = pe[:,0::2] * div_term

tensor([ 4.,  9., 16.])


In [32]:
x =  torch.ones(3, 5,3)
x

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [26]:
y = torch.ones(1, 5)
y

tensor([[1., 1., 1., 1., 1.]])

In [45]:
import torch

# Create a tensor
tensor = torch.arange(12).reshape(3, 4)  # Example tensor of shape (3, 4)

# Define the number of parts (n)
n = 2


print(tensor.size(1))
# Calculate the number of columns per part
columns_per_part = tensor.size(1) // n

# Split the tensor into n parts horizontally
parts = torch.split(tensor, columns_per_part, dim=1)

print(parts)









4
(tensor([[0, 1],
        [4, 5],
        [8, 9]]), tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]]))


In [14]:
original_tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7,8,9]])
original_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [21]:
reshaped_tensor = original_tensor.view(1, 6)
reshaped_tensor

RuntimeError: shape '[1, 6]' is invalid for input of size 9

In [9]:
# Assuming you have a tensor with 8 columns
original_tensor = torch.randn((4,3,12))  # 10 rows, 8 columns

# Reshape into two tensors with 4 columns each
# tensor1 = original_tensor.view(10, 4)
# tensor2 = original_tensor.view(10, 4, 4)

In [10]:
original_tensor

tensor([[[ 0.3747, -0.3154,  1.9973,  1.5016,  0.1367,  0.7747, -0.4879,
          -2.2326, -0.3182, -1.1270, -1.4711, -0.3569],
         [-0.8798,  0.6050,  0.5201,  1.5696, -1.1369,  1.2308, -0.3219,
           1.2360, -0.4541,  0.9117, -1.5560, -0.5282],
         [ 0.0861, -0.6723,  2.0650, -0.3342, -0.1066, -0.9368,  0.0530,
           1.0489,  0.7111, -0.4072, -0.1465,  0.5948]],

        [[-0.5127,  0.5897,  3.1053,  0.6968,  0.6136, -0.1065,  0.1887,
           0.7772,  1.0469,  0.8286, -0.1791,  1.1441],
         [ 0.3378,  0.5325, -0.1929,  0.0176,  0.5653,  1.3824,  1.2239,
           1.4021,  0.2207,  0.1849, -0.9061,  0.4841],
         [ 1.2226,  1.5711, -0.4486,  0.2924,  0.1485, -0.8486, -0.1540,
          -1.4175,  0.2750, -0.7457,  0.3570, -0.7237]],

        [[-0.7684, -0.5854, -1.2868, -0.5021,  0.2955, -1.0912,  0.0700,
           1.5920,  0.0055,  0.3954, -0.1545,  0.1759],
         [ 2.0958, -1.1765,  0.7071,  2.3668,  0.2622, -0.1157, -1.6553,
          -0.3449,  

In [16]:
k = original_tensor.view(original_tensor.shape[0], original_tensor.shape[1], 4, 3).transpose(1,2)
k

tensor([[[[ 0.3747, -0.3154,  1.9973],
          [-0.8798,  0.6050,  0.5201],
          [ 0.0861, -0.6723,  2.0650]],

         [[ 1.5016,  0.1367,  0.7747],
          [ 1.5696, -1.1369,  1.2308],
          [-0.3342, -0.1066, -0.9368]],

         [[-0.4879, -2.2326, -0.3182],
          [-0.3219,  1.2360, -0.4541],
          [ 0.0530,  1.0489,  0.7111]],

         [[-1.1270, -1.4711, -0.3569],
          [ 0.9117, -1.5560, -0.5282],
          [-0.4072, -0.1465,  0.5948]]],


        [[[-0.5127,  0.5897,  3.1053],
          [ 0.3378,  0.5325, -0.1929],
          [ 1.2226,  1.5711, -0.4486]],

         [[ 0.6968,  0.6136, -0.1065],
          [ 0.0176,  0.5653,  1.3824],
          [ 0.2924,  0.1485, -0.8486]],

         [[ 0.1887,  0.7772,  1.0469],
          [ 1.2239,  1.4021,  0.2207],
          [-0.1540, -1.4175,  0.2750]],

         [[ 0.8286, -0.1791,  1.1441],
          [ 0.1849, -0.9061,  0.4841],
          [-0.7457,  0.3570, -0.7237]]],


        [[[-0.7684, -0.5854, -1.2868],
     

In [11]:
#this sapes the tensor into (batch, num_heads, seq_len, d_k)
# 4,4,3,3
j = original_tensor.view(4, 3,4, 3)
j

tensor([[[[ 0.3747, -0.3154,  1.9973],
          [ 1.5016,  0.1367,  0.7747],
          [-0.4879, -2.2326, -0.3182],
          [-1.1270, -1.4711, -0.3569]],

         [[-0.8798,  0.6050,  0.5201],
          [ 1.5696, -1.1369,  1.2308],
          [-0.3219,  1.2360, -0.4541],
          [ 0.9117, -1.5560, -0.5282]],

         [[ 0.0861, -0.6723,  2.0650],
          [-0.3342, -0.1066, -0.9368],
          [ 0.0530,  1.0489,  0.7111],
          [-0.4072, -0.1465,  0.5948]]],


        [[[-0.5127,  0.5897,  3.1053],
          [ 0.6968,  0.6136, -0.1065],
          [ 0.1887,  0.7772,  1.0469],
          [ 0.8286, -0.1791,  1.1441]],

         [[ 0.3378,  0.5325, -0.1929],
          [ 0.0176,  0.5653,  1.3824],
          [ 1.2239,  1.4021,  0.2207],
          [ 0.1849, -0.9061,  0.4841]],

         [[ 1.2226,  1.5711, -0.4486],
          [ 0.2924,  0.1485, -0.8486],
          [-0.1540, -1.4175,  0.2750],
          [-0.7457,  0.3570, -0.7237]]],


        [[[-0.7684, -0.5854, -1.2868],
         

In [35]:
j = original_tensor.view(4, 3,4, 3).transpose(2,1)
j.shape

torch.Size([4, 4, 3, 3])

In [36]:
j = j.transpose(2,1)
j.reshape(j.shape[0], j.shape[1], 3*4)

tensor([[[ 0.3747, -0.3154,  1.9973,  1.5016,  0.1367,  0.7747, -0.4879,
          -2.2326, -0.3182, -1.1270, -1.4711, -0.3569],
         [-0.8798,  0.6050,  0.5201,  1.5696, -1.1369,  1.2308, -0.3219,
           1.2360, -0.4541,  0.9117, -1.5560, -0.5282],
         [ 0.0861, -0.6723,  2.0650, -0.3342, -0.1066, -0.9368,  0.0530,
           1.0489,  0.7111, -0.4072, -0.1465,  0.5948]],

        [[-0.5127,  0.5897,  3.1053,  0.6968,  0.6136, -0.1065,  0.1887,
           0.7772,  1.0469,  0.8286, -0.1791,  1.1441],
         [ 0.3378,  0.5325, -0.1929,  0.0176,  0.5653,  1.3824,  1.2239,
           1.4021,  0.2207,  0.1849, -0.9061,  0.4841],
         [ 1.2226,  1.5711, -0.4486,  0.2924,  0.1485, -0.8486, -0.1540,
          -1.4175,  0.2750, -0.7457,  0.3570, -0.7237]],

        [[-0.7684, -0.5854, -1.2868, -0.5021,  0.2955, -1.0912,  0.0700,
           1.5920,  0.0055,  0.3954, -0.1545,  0.1759],
         [ 2.0958, -1.1765,  0.7071,  2.3668,  0.2622, -0.1157, -1.6553,
          -0.3449,  

In [2]:
aj = torch.randn(3,2)
aj

tensor([[ 1.0987, -0.9672],
        [-0.8051,  1.3027],
        [-0.7114,  0.5448]])

In [4]:
jk =torch.mean(aj, dim=1)
jk.unsqueeze(1)

tensor([[ 0.0657],
        [ 0.2488],
        [-0.0833]])

In [17]:
input_tensor = torch.tensor([[1, 2, 3],
                             [4, 0, 0],
                             [5, 6, 0]])

In [24]:
# Define the padding value
padding_value = 3

# Create the padding mask
padding_mask = (input_tensor != padding_value).int()
print(padding_mask)

masked_tensor = input_tensor * padding_mask

print(masked_tensor)








tensor([[1, 1, 0],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
tensor([[1, 2, 0],
        [4, 0, 0],
        [5, 6, 0]])


In [44]:
j = torch.zeros(5,6)
j

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [45]:
t = torch.ones(3,4, 5,6)
t.shape
f = t * j
print(f)

tensor([[[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0

In [54]:
l = nn.Embedding(10,2, padding_idx=5)
l(torch.tensor([5]))

tensor([[0., 0.]], grad_fn=<EmbeddingBackward0>)

In [8]:
f = torch.ones(3,5)
f



tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [9]:
j = torch.ones(4, 3,5)
j



tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [10]:
f + j

tensor([[[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]],

        [[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]],

        [[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]],

        [[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]]])

In [6]:
mask = torch.zeros(5,3)
mask

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [5]:
p = torch.randn(1,3)
p

tensor([[ 0.5930, -0.3619, -1.9371]])

In [6]:
_, next_WORD = torch.max(p, dim=1)
_


tensor([0.5930])

In [7]:
next_WORD

tensor([0])

In [11]:
p = p.masked_fill(mask == 0, 3)
p

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [3]:
class A():
    def __init__(self, num, num2):
        self.a = num
        self.b = num2
    def sum(self):
        return self.b

In [6]:
A().sum()

TypeError: A.__init__() missing 2 required positional arguments: 'num' and 'num2'